---
global:
  bind: Ivylite
        # Kafka、Cassandra、HBase、MapR、Redis、Ignite、Ivylite
  host: 192.168.0.81,192.168.0.82,192.168.0.83
  clear: false
  prefix: false
#  lib: lib

  work:
    type: write
        # write、read; generate、load; scan
        #   write; read; scan; generate
        #   write read; generate load
        #   write scan load
    total: 1000
    batch: 100
    thread: 1
    throttle: 0
    read_thread: 20

  gen:
    seed: 100
        # rand、uuid、seq、table、fix
    string:
      gen: random
    integer:
      min: 0
      max: 0
    data_path: test
    output:
      file_count: 10
      file_size: -1
    input:
      verify: true

  table:
    schema: String(4), String(100){2}
        # integer @numeric、@sequence
        # string  @random、@fixed、@table、@uuid

        # primary key ((key, column0), column1), index(column4, column5, column6)
        # schema: integer, String(4)[10]<(0, 1), 2>{5-7}
    keyspace: test_space
    table: test
    replica: 1
    read_empty: 0
    read_dump: false

---
cassandra:
  host: 192.168.0.80
  conn_min: 16
  conn_max: 24

  scan_limit: 10000000
  scan_range: 100

  table:
    schema: String(4), String(100)[2]
    keyspace: test_space
    table: test
    replica: 1

    dump_select: true
    read_empty: 10

---
#dump: true
kafka:
  host: 192.168.127.10:9092
  clear: false

  table:
#    schema: integer, string(10/1000) {3}
    schema: string(10), string(30), string(20)
    replica: 1

  gen:
    input:
      verify: false
    output:
      file_rand: false
      file_size: 1g

  work:
    type: read
    total: 100000
    thread: 3
      # write、read; generate、load; scan
    read_thread: 5

  topic:
    name: test
    count: 1
    replica: 1
    partition: 5
    loop: 10000

  producer:
    batch_k: 256
    buffer_m: 64
    linger_ms: 10
    acks: 1

  consumer:
    group: group_test
    client: client-test
#    extract: 1

---
redis:
  host: 192.168.0.81:6379,192.168.0.82,192.168.0.83
  clear: true

  table:
    schema: String(10), String(64)
    read_empty: 0

  work:
    type: write
    total: 100000
    batch: 2
    thread: 10
    throttle: 3000

  gen:
    data_path: ''

  client: lettuce
      # lettuce jedis
  action: data
      # data、list

  async:
    open: false
    wait: false
    outstanding: 1000
    notify: 0
    pool: 0

---
ivylite:
  host: 192.168.127.11
#  file: example-cache.xml
  client: true
#  test: false
#  class: cn.nimblex.ivylite.TreeMapBasedContainer
#  method: dump

  thin:
    open: false
    host: 192.168.127.10:10800

  table:
    schema: String(10), String(64)
#    read_dump: true

  work:
    type: write
    total: 100000
    thread: 10
    batch: 5

    throttle: 0
    read_thread: 2
