---
global:
  bind: Kafka
        # Kafka、Cassandra、HBase、MapR
  host: 192.168.0.81,192.168.0.82,192.168.0.83
  clear: false
  prefix: false

  work:
    type: write
        # write、read; generate、load; scan
        #   write; read; scan; generate
        #   write read; generate load
        #   write scan load
    total: 1000
    batch: 100
    thread: 1
    read_thread: 100

  gen:
    seed: 100
    key_type: rand
        # rand、uuid、seq、table、fix
    data_type: rand

    data_path: test
    output:
      file_count: 10
      file_size: -1

  table:
    schema: String(4), String(100)[2]
        # primary key ((key, column0), column1), index(column4, column5, column6)
        # schema: integer, String(4)[10]<(0, 1), 2>{5-7}
    keyspace: test_space
    table: test
    replica: 1
    read_empty: 1000

---
cassandra:
  host: 192.168.0.80
  conn_min: 16
  conn_max: 24

  scan_limit: 10000000
  scan_range: 100

  table:
    schema: String(4), String(100)[2]
    keyspace: test_space
    table: test
    replica: 1

    dump_select: true
    read_empty: 10

---
#dump: true
kafka:
  host: 192.168.0.81:9092,192.168.0.82:9092,192.168.0.83:9092
  clear: true

  table:
    schema: String(10), String(40960)[1]
    replica: 2

  work:
    type: write
    total: 100
    thread: 1

  gen:
    key_type: rand
    data_type: fix

  topic:
    name: test
    count: 1
    partition: 5
    loop: 10000

  producer:
    batch_k: 256
    buffer_m: 64
    linger_ms: 10
    acks: 1

  consumer:
    group: group_test
    client: client-test

---
redis:
  host: 192.168.0.81:6379,192.168.0.82,192.168.0.83
  clear: true

  table:
    schema: String(10), String(64)
    read_empty: 0

  work:
    type: write
    total: 10000
    batch: 1
    thread: 3

  gen:
    key_type: table
    data_type: fix
    data_path: ''

  client: lettuce
      # lettuce jedis
  action: data
      # data、list

  async:
    open: true
    wait: false
    outstanding: 1000
    notify: 0
    pool: 0
