---
flink:
  config:
    parallelism: 1
    # 连接到数据库获取规则之前，每个taskManager上可以保留的Event的个数
    unordered: 100000

  debug:
    test: true
    count: 10000
    wait: 2000
    # 是否输出报警的match信息
    logging: true

  kafka:
    topic: test
    group: test
    server: 192.168.0.81:9092
    Earliest: true

  database:
    topic: rule
    group: test
    server: 192.168.0.81:9092
